-- MySQL Script generated by MySQL Workbench
-- Thu Oct 23 18:05:43 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema integrador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema integrador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `integrador` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `integrador` ;

-- -----------------------------------------------------
-- Table `integrador`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integrador`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(100) NULL DEFAULT NULL,
  `iso` VARCHAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador`.`record_label`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integrador`.`record_label` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `country_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `country_id` (`country_id` ASC) VISIBLE,
  CONSTRAINT `record_label_ibfk_1`
    FOREIGN KEY (`country_id`)
    REFERENCES `integrador`.`country` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 59
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador`.`artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integrador`.`artist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integrador`.`album` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  `year` INT NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `id_artist` INT NULL DEFAULT NULL,
  `id_label` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_artist` (`id_artist` ASC) VISIBLE,
  INDEX `id_label` (`id_label` ASC) VISIBLE,
  CONSTRAINT `album_ibfk_10`
    FOREIGN KEY (`id_label`)
    REFERENCES `integrador`.`record_label` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `album_ibfk_9`
    FOREIGN KEY (`id_artist`)
    REFERENCES `integrador`.`artist` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 56
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integrador`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` TEXT NOT NULL,
  `create_time` DATETIME NULL DEFAULT NULL,
  `gender` VARCHAR(9) NULL DEFAULT NULL,
  `birth_date` DATE NULL DEFAULT NULL,
  `zipcode` INT NULL DEFAULT NULL,
  `pass_updated_at` DATETIME NULL DEFAULT NULL,
  `country_id` INT NULL DEFAULT NULL,
  `role` ENUM('FREE', 'PREMIUM', 'ADMIN') NOT NULL DEFAULT 'FREE' COMMENT 'Rol del usuario: FREE, PREMIUM, ADMIN',
  `is_deleted` TINYINT(1) NULL DEFAULT '0',
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `email_2` (`email` ASC) VISIBLE,
  UNIQUE INDEX `email_3` (`email` ASC) VISIBLE,
  UNIQUE INDEX `email_4` (`email` ASC) VISIBLE,
  UNIQUE INDEX `email_5` (`email` ASC) VISIBLE,
  INDEX `country_id` (`country_id` ASC) VISIBLE,
  CONSTRAINT `user_ibfk_1`
    FOREIGN KEY (`country_id`)
    REFERENCES `integrador`.`country` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador`.`payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integrador`.`payment_method` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `last_four_digits` VARCHAR(4) NOT NULL,
  `expiration_date` DATE NULL DEFAULT NULL,
  `is_primary` TINYINT(1) NULL DEFAULT '0',
  `token` VARCHAR(45) NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `payment_method_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `integrador`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador`.`subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integrador`.`subscription` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(9) NOT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `renewal_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `subscription_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `integrador`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador`.`billing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integrador`.`billing` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,2) NULL DEFAULT NULL,
  `renewed_times` INT NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `payment_method_id` INT NULL DEFAULT NULL,
  `subscription_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `payment_method_id` (`payment_method_id` ASC) VISIBLE,
  INDEX `subscription_id` (`subscription_id` ASC) VISIBLE,
  CONSTRAINT `billing_ibfk_13`
    FOREIGN KEY (`user_id`)
    REFERENCES `integrador`.`user` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `billing_ibfk_14`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `integrador`.`payment_method` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `billing_ibfk_15`
    FOREIGN KEY (`subscription_id`)
    REFERENCES `integrador`.`subscription` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integrador`.`genre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador`.`song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integrador`.`song` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `duration` INT NULL DEFAULT NULL,
  `views` INT NULL DEFAULT NULL,
  `likes` INT NULL DEFAULT NULL,
  `id_album` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_album` (`id_album` ASC) VISIBLE,
  CONSTRAINT `song_ibfk_1`
    FOREIGN KEY (`id_album`)
    REFERENCES `integrador`.`album` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 141
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador`.`listening_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integrador`.`listening_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `played_at` DATETIME NULL DEFAULT NULL,
  `completed` TINYINT(1) NULL DEFAULT '0',
  `user_id` INT NULL DEFAULT NULL,
  `song_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `song_id` (`song_id` ASC) VISIBLE,
  CONSTRAINT `listening_history_ibfk_10`
    FOREIGN KEY (`song_id`)
    REFERENCES `integrador`.`song` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `listening_history_ibfk_9`
    FOREIGN KEY (`user_id`)
    REFERENCES `integrador`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integrador`.`playlist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `is_deleted` TINYINT(1) NULL DEFAULT '0',
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `create_time` DATETIME NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `playlist_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `integrador`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador`.`playlist_song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integrador`.`playlist_song` (
  `song_id` INT NOT NULL,
  `playlist_id` INT NOT NULL,
  `order_in_playlist` INT NULL DEFAULT NULL,
  `added_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`song_id`, `playlist_id`),
  UNIQUE INDEX `playlist_song_song_id_playlist_id_unique` (`song_id` ASC, `playlist_id` ASC) VISIBLE,
  INDEX `playlist_id` (`playlist_id` ASC) VISIBLE,
  CONSTRAINT `playlist_song_ibfk_1`
    FOREIGN KEY (`song_id`)
    REFERENCES `integrador`.`song` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `playlist_song_ibfk_2`
    FOREIGN KEY (`playlist_id`)
    REFERENCES `integrador`.`playlist` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador`.`song_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integrador`.`song_genre` (
  `song_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`song_id`, `genre_id`),
  UNIQUE INDEX `song_genre_genre_id_song_id_unique` (`song_id` ASC, `genre_id` ASC) VISIBLE,
  INDEX `genre_id` (`genre_id` ASC) VISIBLE,
  CONSTRAINT `song_genre_ibfk_1`
    FOREIGN KEY (`song_id`)
    REFERENCES `integrador`.`song` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `song_genre_ibfk_2`
    FOREIGN KEY (`genre_id`)
    REFERENCES `integrador`.`genre` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
